# Generated by Django 4.2.5 on 2023-10-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='This is deleted datetime', null=True, verbose_name='Deleted datetime')),
                ('restored_at', models.DateTimeField(blank=True, editable=False, help_text='This is Restored Datetime', null=True, verbose_name='Restored Datetime')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('rss_url', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=256, null=True)),
                ('generator', models.CharField(blank=True, max_length=256, null=True)),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=256, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=256, null=True)),
                ('explicit', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, max_length=256, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('icon_image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('image_link', models.CharField(blank=True, max_length=256, null=True)),
                ('image_title', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='This is deleted datetime', null=True, verbose_name='Deleted datetime')),
                ('restored_at', models.DateTimeField(blank=True, editable=False, help_text='This is Restored Datetime', null=True, verbose_name='Restored Datetime')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('episode_num', models.CharField(blank=True, max_length=256, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('publish_date', models.CharField(blank=True, max_length=256, null=True)),
                ('explicit', models.CharField(blank=True, max_length=256, null=True)),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=256, null=True)),
                ('enclosure_url', models.CharField(blank=True, max_length=512, null=True)),
                ('enclosure_type', models.CharField(blank=True, max_length=256, null=True)),
                ('enclosure_length', models.CharField(blank=True, max_length=256, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='podcast.podcast')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
