# Generated by Django 4.2.5 on 2023-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='rss_url',
            field=models.CharField(max_length=200),
        ),
    ]
