# Generated by Django 4.2.5 on 2023-09-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_alter_podcastepisode_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisode',
            name='episode_type',
        ),
    ]
