# Generated by Django 4.2.5 on 2023-09-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_alter_podcast_author_alter_podcast_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='guid',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
